My branch
ArwaAshawy/JavaScript-Quiz pull request #7
Opened 2021-03-11 15:17 UTC by ArwaAshawy

2021-03-11 19:25 UTC, EmadMokhtar requested changes
Remove the empty js file.

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com">
Duplicate link tag

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +                </div> -->
Commented code

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +        const thanksView = document.querySelector('#thanks-view')
Rename vars to include the tag

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +        const thanksView = document.querySelector('#thanks-view')
Exclude `counterDiv` `quizView` and `thanksView`

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +            "Welcome to JS quiz\n Here are the rules: \n 1 -Don't select the same answer twice.\n2- If all your answers are wrong, you will not get a feedback abput how many question(s) ypu answered.
This is a very long line. Think about a solution to make it short and readable.

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +        }
- Split the function into 2 functions (Single Responsiblity).
- Start button click ->  `startTheQuiz()`.
- End button click -> `endTheQuiz()`.

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +            // let p = document.createElement('p');
Commented code.

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +            const p = document.createElement('p');
```suggestion
            const pElement = document.createElement('p');
```

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +            const text = document.createTextNode(`You got ${total} correct(s) from 9`);
Choose a more descriptive name.
```suggestion
            const scoreText = document.createTextNode(`You got ${total} correct(s) from 9`);
```

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +        let questions = quiz;
Move the variable abovee

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +                question.classList.toggle('hidden');
Use remove instead of a toggle. Check the below lines as well.

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +        function showQuestion() {
What about adding a jsdocs to the functions? For VS code check the [link](https://code.visualstudio.com/Docs/languages/javascript#_jsdoc-support)

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +                //not to repeat the sama choice twice
```suggestion
                //not to repeat the same choice twice
```

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +            //not to repeat the sama question twice
```suggestion
            //not to repeat the same question twice
```

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +        // exitBtn.addEventListener('click', showThankYou);
Commented code

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +                if (choice.dataset.answer == 'true') {
```suggestion
                if (choice.dataset.answer === 'true') {
```

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +            if (this.dataset.answer == 'true') {
```suggestion
            if (this.dataset.answer === 'true') {
```

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +            elm.classList.add('wrong');
Try to follow the BS naming convestion, for example `wrong` -> `bg-red`.

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +        function wrong(elm) {
```suggestion
        function markWrongAnswer(elm) {
```

2021-03-11 19:25 UTC, EmadMokhtar commented on index.html
> +        function correct(elm) {
```suggestion
        function markCorrectAnswer(elm) {
```

2021-03-11 21:58 UTC, ArwaAshawy commented on index.html
> +            "Welcome to JS quiz\n Here are the rules: \n 1 -Don't select the same answer twice.\n2- If all your answers are wrong, you will not get a feedback abput how many question(s) ypu answered.
couldn't find a solution other than this

2021-03-18 19:51 UTC, EmadMokhtar commented on index.html
> +            "Welcome to JS quiz\n Here are the rules: \n 1 -Don't select the same answer twice.\n2- If all your answers are wrong, you will not get a feedback abput how many question(s) ypu answered.
No worries this is fine.

2021-03-18 20:20 UTC, EmadMokhtar approved these changes
Well done

2021-03-18 20:23 UTC, merged